# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.

# Process vis.mac (and draw geometry)
/control/execute vis.mac

# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit

# View menu:
/gui/addMenu view View
/gui/addButton view "X-Y" "/vis/viewer/set/viewpointVector 0 0 1"
/gui/addButton view "Y-Z" "/vis/viewer/set/viewpointVector 1 0 0"

# Run menu :
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run "reinitialize" "/run/reinitializeGeometry 0"

# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "0.5 MeV"  "/gun/energy 0.5 MeV"
/gui/addButton gun "5 MeV"  "/gun/energy 5 MeV"
/gui/addButton gun "50 MeV"   "/gun/energy 50 MeV"
/gui/addButton gun "500 MeV"   "/gun/energy 500 MeV"
/gui/addButton gun "5 GeV"   "/gun/energy 5 GeV"
/gui/addButton gun "e-"     "/gun/particle e-"
/gui/addButton gun "mu-"      "/gun/particle mu-"
/gui/addButton gun "neutron" "/gun/particle neutron"
/gui/addButton gun "proton"  "/gun/particle proton"
/gui/addButton gun "K+"  "/gun/particle kaon+"
/gui/addButton gun "pi+"  "/gun/particle pi+"
/gui/addButton gun "pi0"     "/gun/particle pi0"


# Photon menu
/gui/addMenu photon Photon
/gui/addButton photon "Cerenkov On" "/process/activate Cerenkov"
/gui/addButton photon "Cerenkov Off" "/process/inactivate Cerenkov"
/gui/addButton photon "Scintillation On" "/process/activate Scintillation"
/gui/addButton photon "Scintillation Off" "/process/inactivate Scintillation"
/gui/addButton photon "scintillation 100 ph./MeV" "/detector/scYield 100"
/gui/addButton photon "scintillation 10000 ph./MeV" "/detector/scYield 1000"




